mitmproxy_wrapper: run mitmproxy / mitmdump as transparent proxy on linux
moved transparent proxy logic to mitmproxy_wrapper,
urldump can just call mitmproxy_wrapper

diff --git a/urldump b/urldump
--- a/urldump
+++ b/urldump
@@ -1,7 +1,6 @@
 #!/bin/bash
 # urldump
-# Dump http(s) requests system-wide, and from lan devices as well when
-# running on a router.
+# Dump http(s) requests system-wide and from lan devices as well on a router.
 #
 # Uses mitmproxy so works for https too.
 # iptables is used to transparently redirect all traffic to proxy.
@@ -10,106 +9,59 @@
 # Must be run as root.
 # mitmdump can (should) be run as a different user, see below.
 #
-# For more info see:
+# more info:
 #   https://github.com/lemonsqueeze/urldump
 
 usage()
 {
-    echo "usage:"
-    echo "  urldump		  dump http(s) requests system-wide"
-    echo "  urldump --router      also show requests from lan devices behind router"
+    echo "usage:  urldump [options]"
+    echo ""
+    echo "options:"
+    echo "  --local         show local traffic only"
+    echo "  --router        also capture traffic from lan devices behind router."
+    echo "                  default: enabled if host is forwarding traffic"
+    echo "  --user name	    user to run mitmproxy as"
+    echo "  --mitmdump path specify mitmdump location"
+    echo ""
+    echo "if mitmdump fails try installing recent mitmproxy package (7.0.3)"
     exit 1
 }
 
-# User to run mitmproxy as. Beware that requests from this user won't be logged.
-# If you care about security create a non root user.
-user=root
-#user=mitmproxy
+die()   {  echo "urldump:" "$@" 1>&2; exit 1;  }
 
-# Network interfaces when running in router mode:
-LAN_IF=		# lan interface
-NET_IF=		# internet interface
+mitmdump="mitmdump"
 
-debug=""
-#debug=y
+# save arguments
+args="$@"
 
-die()   {  echo "$@"; exit 1;  }
-debug() {  if [ -n "$debug" ]; then echo "$@"; fi;  }
+while [ "${1#-}" != "$1" ]; do
+    opt="$1"; shift
+    [ "$opt" = "--help" ] && usage
+    [ "$opt" = "-h" ]    && usage
 
-[ "$1" = "--help" ] && usage
-[ "$1" = "--h" ]    && usage
-
-router=""
-if [ "$1" = "--router" ]; then
-    shift;  router="y"
-    [ -n "$LAN_IF" ] || die "need to set LAN_IF (lan interface)"
-    [ -n "$NET_IF" ] || die "need to set NET_IF (internet interface)"
-    nat=`iptables-save | grep MASQUERADE`
-fi
-
-[ $# = 0 ] || usage
-
-
-# Sanity checks
-type mitmdump > /dev/null  || die "mitmdump not found, install mitmproxy package first."
-type iptables > /dev/null  || die "iptables not found, aborting."
-[ `id -u` = 0 ] || die "Must run as root, aborting."
-
-cleanup() {  echo ""; debug "Cleaning up"; }
-trap cleanup int
-
-# save tables
-iptables-save > /tmp/urldump.iptables
-
-# reset tables
-for f in filter nat mangle; do
-    iptables -t $f -F
-    iptables -t $f -X
-    iptables -t $f -F
-done
-iptables -P INPUT ACCEPT
-iptables -P OUTPUT ACCEPT
-iptables -P FORWARD ACCEPT
-
-
-# Redirect local http & https requests to proxy
-iptables -t nat -A OUTPUT  -p tcp -m owner --uid-owner $user -j ACCEPT
-iptables -t nat -A OUTPUT  -p tcp --dport 80 -j REDIRECT --to-port 8080
-iptables -t nat -A OUTPUT  -p tcp --dport 443 -j REDIRECT --to-port 8080
-# block udp ...
-iptables -A OUTPUT  -p udp --dport 80 -j REJECT
-iptables -A OUTPUT  -p udp --dport 443 -j REJECT
-
-# Router: Redirect http & https requests from LAN to proxy
-if [ -n "$router" ]; then
-    iptables -t nat -A PREROUTING -i $LAN_IF -p tcp --dport 80  -j REDIRECT --to-port 8080
-    iptables -t nat -A PREROUTING -i $LAN_IF -p tcp --dport 443 -j REDIRECT --to-port 8080
-    # ip6tables -t nat -A PREROUTING -i $LAN_IF -p tcp --dport 80  -j REDIRECT --to-port 8080
-    # ip6tables -t nat -A PREROUTING -i $LAN_IF -p tcp --dport 443 -j REDIRECT --to-port 8080
-    # block udp ...
-    iptables -A FORWARD  -p udp --dport 80 -j REJECT
-    iptables -A FORWARD  -p udp --dport 443 -j REJECT
-
-    # need this for nat
-    if [ -n "$nat" ]; then
-	iptables -t nat -A POSTROUTING -o $NET_IF -j MASQUERADE
+    if [ "$opt" = "--mitmdump" ]; then
+	mitmdump="$1"; shift
     fi
-    echo "capturing local and lan traffic"
-else
-    echo "capturing local traffic only"
+    
+    # skip others, only care about --mitmdump here
+    [ "$opt" = "--user" ] && shift
+done
+
+# we need mitmproxy wrapper script
+mitmproxy_wrapper="mitmproxy_wrapper"
+if ! type "$mitmproxy_wrapper" >/dev/null 2>&1; then
+    dir="${BASH_SOURCE%/*}"
+    mitmproxy_wrapper="$dir/mitmproxy_wrapper"
+    type "$mitmproxy_wrapper" >/dev/null 2>&1 || die "mitmproxy_wrapper not found"
 fi
 
-
-debug "Starting mitmdump ..."
-cmd="mitmdump -T --host"	# Transparent proxy
-
-
-if [ $user = "root" ]; then
-                        $cmd | grep --line-buffered ' http'  | cut -d\  -f3-
-else
-    sudo -n -H -u $user $cmd | grep --line-buffered ' http'  | cut -d\  -f3-
+if ! type "$mitmdump" >/dev/null 2>&1; then
+    die "mitmdump command not found '$mitmdump'"
 fi
 
-# restore tables
-iptables-restore /tmp/urldump.iptables
+# mitmdump command
+cmd="$mitmdump --mode transparent --showhost"	# transparent proxy  (recent mitmproxy versions)
+#cmd="mitmdump -T --host"			# transparent proxy  (old mitmproxy versions)
+
+$mitmproxy_wrapper "$@" $cmd | grep --line-buffered ' http'  | cut -d\  -f3-
 
